#!/usr/bin/env bash
# Установка pre-push hook.
#
# Использование:
#   bash scripts/install_pre_push_hook.sh
#   bash scripts/install_pre_push_hook.sh --force   # усыновить/заменить чужой (без маркера) hook
#
# Отказы (exit 1, ничего не создаётся) — в этом порядке, --force НЕ обходит ни
# один из них (кроме случая 3, для которого он и существует):
#   1) core.hooksPath задан — git не запускает .git/hooks; подключи
#      scripts/hooks/pre-push к тому каталогу хуков самостоятельно.
#   2) путь хука ИЛИ его каталог — symlink — claude-kit никогда не пишет через ссылку.
#   3) уже существует чужой (без маркера) hook — передай --force, чтобы усыновить его.
#
# Сгенерированный hook пересобирается при каждом install/upgrade — правь
# scripts/hooks/pre-push, а не сгенерированный .git/hooks/pre-push.
#
# Hook блокирует `git push` при:
#   1) тесты в ветке менялись, но нет записи инъекции (Task 6.2) — гейт стоит
#      ПЕРВЫМ, см. блок ниже
#   2) нарушении правил из .sentrux/rules.toml (sentrux check)
#   3) структурной регрессии относительно baseline (sentrux gate)
#
# Обновить baseline после намеренного улучшения:
#   sentrux gate --save
#
# Обойти уже установленный hook (только в крайних случаях):
#   git push --no-verify

set -e

# Единственное место, где живёт отпечаток «это наш hook» — grep-проверка ниже
# и сгенерированная строка маркера читают одну и ту же переменную (review
# Task 3.11 finding 3), так что рассинхрон между ними больше невозможен.
# Значение зеркалит claude_kit_core.postinstall.SEED_PRE_PUSH_HOOK_MARKER —
# тест держит их равными.
MARKER="Auto-generated by install_pre_push_hook.sh"

REPO_ROOT="$(git rev-parse --show-toplevel)"

# core.hooksPath меняет каталог, которым пользуется сам git; `--git-path`
# ниже это учитывает и охотно резолвит DST внутрь него — раньше здесь ничего
# не мешало установщику писать именно туда (review finding 5, расхождение с
# Python-стороной). Политика теперь одна: core.hooksPath задан -> отказ, без
# обхода через --force, ничего не создаётся (ни .git/hooks, ни каталог
# hooksPath).
HOOKS_PATH="$(git config --get core.hooksPath 2>/dev/null || true)"
if [ -n "$HOOKS_PATH" ]; then
    echo "error: core.hooksPath is set ($HOOKS_PATH) — git does not run .git/hooks; pre-push hook not installed. Wire scripts/hooks/pre-push into that hooks directory" >&2
    exit 1
fi

DST="$(git rev-parse --git-path hooks/pre-push)"

# A symlink is refused BEFORE its body is read or `mkdir -p` runs — either the
# hook itself or its containing directory (a symlinked `.git/hooks` — the
# write would otherwise land wherever that link points, possibly OUTSIDE the
# project — review Task 3.11 finding 1). claude-kit never writes through a
# link (same rule as claude_kit_core.postinstall's git-hook installers), and
# --force never bypasses this (only the foreign-hook check below). This path
# is also reachable directly, via /mcp-sentrux:install-pre-push, without the
# Python pre-checks in front of it.
if [ -L "$DST" ] || [ -L "$(dirname "$DST")" ]; then
    echo "error: pre-push hook path $DST is a symlink — claude-kit never writes through a link" >&2
    exit 1
fi

# A foreign (unmarked) hook is left to its owner unless the caller passes
# --force.
if [ -e "$DST" ] && ! grep -qF "$MARKER" "$DST" && [ "${1:-}" != "--force" ]; then
    echo "foreign pre-push hook left untouched: $DST — call scripts/hooks/pre-push from it, or re-run with --force" >&2
    exit 1
fi

mkdir -p "$(dirname "$DST")"

# Тело structural-гейта ищем по тем же трём кандидатам и в том же порядке, что
# блок инъекций ниже ищет check_injections.py — один способ резолвинга на файл,
# не два. Порядок: проектная копия (её юзер вправе править) → путь плагина (у
# проекта, получившего `.claude/` через `init`, `scripts/` может быть пустым) →
# дерево сида (этот репозиторий dogfood'ит собственный шаблон).
SRC=""
for _cand in "$REPO_ROOT"/scripts/hooks/pre-push \
             "$REPO_ROOT"/.claude/plugins/core/templates/scripts/hooks/pre-push \
             "$REPO_ROOT"/src/*/template/plugins/core/templates/scripts/hooks/pre-push; do
    if [ -f "$_cand" ]; then SRC="$_cand"; break; fi
done

if [ -z "$SRC" ]; then
    echo "error: тело хука pre-push не найдено ни в scripts/hooks/, ни в .claude/plugins/core/templates/scripts/hooks/" >&2
    exit 1
fi

# Собираем hook как «injections-гейт + тело sentrux», а НЕ дописыванием в конец.
# Дописанный блок был мёртвым кодом: тело sentrux заканчивается `exit 0` (и
# выходит раньше, если sentrux не установлен), поэтому гейт не выполнялся
# никогда — ни на одной машине. Порядок «сначала дешёвая проверка записи,
# потом структурный анализ» заодно экономит время на заведомо блокируемом push.
#
# Блок ниже — ЕДИНСТВЕННЫЙ источник правды для этой проверки; тот же текст
# дословно лежит в `/dev:ship` (шаг 2), и тест
# `tests/unit/test_injections_gate.py::test_ship_md_embeds_the_same_gate_block_as_the_hook`
# держит две копии byte-identical. Вся логика — в одном Python-файле
# (`scripts/validate_commit/check_injections.py`), здесь только plumbing:
# найти скрипт и интерпретатор.
{
    echo '#!/usr/bin/env bash'
    echo "# $MARKER — НЕ редактировать вручную."
    echo '# Порядок: injections-record gate (Task 6.2) → structural gate (sentrux).'
    echo ''
    cat <<'PRE_PUSH_INJECTIONS_GATE'
# --- injections-record gate (Task 6.2) --------------------------------------
# The branch changed tests/** → its plan must carry a filled-in row
# `property | predicted red | observed red`. The logic lives in one place,
# scripts/validate_commit/check_injections.py, so pre-push and /dev:ship cannot
# disagree on what counts as a record. This block only locates the script and
# an interpreter; if either is missing, the gate says so out loud instead of
# silently letting the push through.
_repo_root="$(git rev-parse --show-toplevel 2>/dev/null || echo .)"
_inj_check=""
for _cand in "$_repo_root"/scripts/validate_commit/check_injections.py \
             "$_repo_root"/src/*/template/plugins/lang-python/templates/validate_commit/check_injections.py; do
  if [ -f "$_cand" ]; then _inj_check="$_cand"; break; fi
done
_inj_py=""
for _cand in "${CLAUDE_PYTHON_BIN:-}" python3 python py; do
  [ -n "$_cand" ] || continue
  if command -v "$_cand" >/dev/null 2>&1 && "$_cand" -c "import sys" >/dev/null 2>&1; then
    _inj_py="$_cand"; break
  fi
done
if [ -z "$_inj_check" ]; then
  echo "WARN: injections-record gate skipped — check_injections.py not found (scripts/validate_commit/)" >&2
elif [ -z "$_inj_py" ]; then
  echo "WARN: injections-record gate skipped — no working Python on PATH" >&2
elif ! "$_inj_py" "$_inj_check"; then
  exit 1
fi
# --- end injections-record gate ---------------------------------------------
PRE_PUSH_INJECTIONS_GATE
    echo ''
    # Тело structural-гейта без его shebang (первая строка).
    tail -n +2 "$SRC"
} >"$DST"

chmod +x "$DST"

echo "✓ Установлен pre-push hook: $DST"
echo ""
echo "Проверь работу:"
echo "  bash $DST"
