# -*- coding: utf-8 -*-
"""
Central PyQt5 imports for frontend_module.

Requires PyQt5. Fail-fast if not installed.
"""
from PyQt5.QtCore import QObject, Qt, QSize, QTimer, QThread, pyqtSignal
from PyQt5.QtGui import (
    QCloseEvent,
    QCursor,
    QDoubleValidator,
    QFont,
    QIcon,
    QImage,
    QIntValidator,
    QPixmap,
)
from PyQt5.QtWidgets import (
    QAbstractItemView,
    QApplication,
    QCheckBox,
    QComboBox,
    QDoubleSpinBox,
    QFrame,
    QGroupBox,
    QGridLayout,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QListWidget,
    QMainWindow,
    QMessageBox,
    QProgressBar,
    QPushButton,
    QScrollArea,
    QSizePolicy,
    QSlider,
    QStackedWidget,
    QTabWidget,
    QTableWidget,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
)

__all__ = [
    "QAbstractItemView",
    "QApplication",
    "QCloseEvent",
    "QCheckBox",
    "QComboBox",
    "QDoubleSpinBox",
    "QDoubleValidator",
    "QFrame",
    "QGroupBox",
    "QGridLayout",
    "QHeaderView",
    "QHBoxLayout",
    "QIcon",
    "QImage",
    "QIntValidator",
    "QLabel",
    "QLineEdit",
    "QListWidget",
    "QMainWindow",
    "QMessageBox",
    "QObject",
    "QProgressBar",
    "QPixmap",
    "QPushButton",
    "QScrollArea",
    "QSize",
    "QSizePolicy",
    "QSlider",
    "QStackedWidget",
    "QTabWidget",
    "QTableWidget",
    "QTableWidgetItem",
    "QThread",
    "QTimer",
    "QVBoxLayout",
    "QWidget",
    "Qt",
    "QCursor",
    "QFont",
    "pyqtSignal",
]
