#!/usr/bin/env bash
# Установка commit-msg hook для валидации commit-сообщений.
# Запуск: bash scripts/validate_commit/install_hook.sh
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_PATH="$REPO_ROOT/.git/hooks/commit-msg"

cat > "$HOOK_PATH" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/validate_commit/install_hook.sh
# Валидирует commit-сообщение по правилам Inspector_bottles.
exec python3 "$(git rev-parse --show-toplevel)/scripts/validate_commit/validate_commit.py" "$1"
EOF

chmod +x "$HOOK_PATH"
echo "✅ commit-msg hook установлен: $HOOK_PATH"
echo "   Проверка: git commit (без -m) откроет шаблон .gitmessage"
echo "   Bypass: git commit --no-verify (только для merge/rebase)"
