"""render_context.py — сводка per-module CONTEXT.md в root registry.

Парсит CONTEXT.md модулей, извлекает Purpose (первый параграф под `## Purpose`)
и счётчик секций. Рендерит таблицу в `docs/PROJECT_CONTEXT.md` между маркерами:

    <!-- CONTEXT-INDEX:BEGIN — generated by aggregate_context — DO NOT EDIT -->
    | Модуль | Purpose | Секции | Файл |
    | ...
    <!-- CONTEXT-INDEX:END -->

Какие секции считаются «известными» (опц. наличие отображается чекмарком):
- Purpose, Key decisions, Gotchas, Glossary, Open questions, Migration notes.

Custom-секции игнорируются для табличного индекса (но видны в исходном файле).
"""

from __future__ import annotations

import re
from pathlib import Path

from collections.abc import Sequence

from .discover import ModuleEntry, discover_modules


KNOWN_SECTIONS: tuple[str, ...] = (
    "Purpose",
    "Key decisions",
    "Gotchas",
    "Glossary",
    "Open questions",
    "Migration notes",
)

_SECTION_RE = re.compile(r"^##\s+(.+?)\s*$", re.MULTILINE)
_PURPOSE_BLOCK_RE = re.compile(
    r"^##\s+Purpose\s*\n+(.+?)(?=\n##\s+|\Z)",
    re.MULTILINE | re.DOTALL,
)


def _extract_sections(text: str) -> set[str]:
    """Возвращает множество H2-заголовков из CONTEXT.md."""
    return {m.group(1).strip() for m in _SECTION_RE.finditer(text)}


def _extract_purpose(text: str) -> str:
    """Извлекает первый параграф под `## Purpose`.

    Возвращает обрезанную (до 120 символов) одну строку или '—' если
    Purpose отсутствует или пуст.
    """
    match = _PURPOSE_BLOCK_RE.search(text)
    if not match:
        return "—"
    block = match.group(1).strip()
    first_para = block.split("\n\n", 1)[0].strip()
    one_line = " ".join(first_para.split())
    if len(one_line) > 120:
        one_line = one_line[:117] + "…"
    return one_line or "—"


def _section_marks(sections: set[str]) -> str:
    """Строит компактную строку с маркерами наличия известных секций.

    'P✓ K✓ G− Gl− O− M−' — Purpose+Key decisions есть, остальные нет.
    """
    abbrev = {
        "Purpose": "P",
        "Key decisions": "K",
        "Gotchas": "G",
        "Glossary": "Gl",
        "Open questions": "O",
        "Migration notes": "M",
    }
    parts = []
    for section in KNOWN_SECTIONS:
        marker = "✓" if section in sections else "−"
        parts.append(f"{abbrev[section]}{marker}")
    return " ".join(parts)


class RenderContext:
    """SyncModule: per-module CONTEXT.md → root PROJECT_CONTEXT.md table."""

    name = "render_context"
    description = "Сводка CONTEXT.md модулей в docs/PROJECT_CONTEXT.md"

    def __init__(
        self,
        root: Path,
        target_file: Path,
        *,
        modules: Sequence[ModuleEntry] | None = None,
    ):
        """Args:
        root: корень проекта.
        target_file: путь к root registry (обычно docs/PROJECT_CONTEXT.md).
        modules: опционально — заранее найденные модули (избегает повторного
            rglob если несколько рендереров делят один discovery-результат).
            Если None — вызываем discover_modules сами.
        """
        self.root = Path(root).resolve()
        self.target_file = Path(target_file)
        self._modules = modules

    def render(self) -> dict[Path, dict[str, str]]:
        source = (
            self._modules if self._modules is not None else discover_modules(self.root)
        )
        modules = [m for m in source if m.context_file is not None]

        if not modules:
            content = (
                "_Не найдено ни одного CONTEXT.md. "
                "Создай `<module>/CONTEXT.md` из шаблона "
                "`.claude/plugins/core/templates/CONTEXT.template.md`._"
            )
            return {self.target_file: {"CONTEXT-INDEX": content}}

        lines = [
            "| Модуль | Purpose | Секции (P K G Gl O M) | Файл |",
            "|--------|---------|------------------------|------|",
        ]
        for mod in modules:
            assert mod.context_file is not None
            text = mod.context_file.read_text(encoding="utf-8")
            purpose = _extract_purpose(text)
            sections = _extract_sections(text)
            marks = _section_marks(sections)
            rel_path = mod.context_file.relative_to(self.root).as_posix()
            lines.append(
                f"| `{mod.name}` | {purpose} | {marks} | [`{rel_path}`]({rel_path}) |"
            )

        content = "\n".join(lines)
        return {self.target_file: {"CONTEXT-INDEX": content}}
