#!/usr/bin/env bash
# Install commit-msg hook: validates commit messages via validate_commit.py.
# Usage: bash scripts/validate_commit/install_hook.sh
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_PATH="$REPO_ROOT/.git/hooks/commit-msg"

cat > "$HOOK_PATH" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/validate_commit/install_hook.sh
#
# Pick a working Python interpreter. On Windows `python3` often resolves to the
# Microsoft Store App Installer stub which prints "Python " and exits 1 in
# non-interactive shells — that silently breaks the hook. Same detection
# strategy as .claude/hooks/_lib/python-bin.sh.
if [[ -n "${CLAUDE_PYTHON_BIN:-}" ]] && command -v "$CLAUDE_PYTHON_BIN" >/dev/null 2>&1; then
  PY="$CLAUDE_PYTHON_BIN"
elif command -v python3 >/dev/null 2>&1 && python3 -c "import sys" >/dev/null 2>&1; then
  PY="python3"
elif command -v python >/dev/null 2>&1; then
  PY="python"
elif command -v py >/dev/null 2>&1; then
  PY="py -3"
else
  echo "commit-msg: no working Python interpreter found on PATH" >&2
  exit 1
fi

exec "$PY" "$(git rev-parse --show-toplevel)/scripts/validate_commit/validate_commit.py" "$1"
EOF

chmod +x "$HOOK_PATH"
echo "✅ commit-msg hook installed: $HOOK_PATH"
echo "   Bypass (merge/rebase only): git commit --no-verify"
