# СГЕНЕРИРОВАНО из Services/robot_comm/protocols/delta_v2.yaml (6f7b966e)
# не править руками; python -m Services.robot_comm.codegen

from __future__ import annotations

import math

from typing import Annotated

from pydantic import Field

from multiprocess_framework.modules.data_schema_module import FieldMeta, SchemaBase

PARAMS = {
    0: {
        'name': 'P_SPD_DEFAULT',
        'label': 'Override по умолчанию',
        'unit': '%',
        'scale': 1,
        'signed': False,
        'min': 1,
        'max': 100,
        'default': 80,
        'group': 0,
        'apply': 'live',
        'info': '',
        'gate1': False,
    },
    1: {
        'name': 'P_SPD_JOG',
        'label': 'Override для JOG',
        'unit': '%',
        'scale': 1,
        'signed': False,
        'min': 1,
        'max': 100,
        'default': 30,
        'group': 0,
        'apply': 'live',
        'info': '',
        'gate1': False,
    },
    2: {
        'name': 'P_SPD_L',
        'label': 'SpdL',
        'unit': 'мм/с',
        'scale': 1,
        'signed': False,
        'min': 10,
        'max': 3000,
        'default': 1500,
        'group': 0,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    3: {
        'name': 'P_ACC_L',
        'label': 'AccL/DecL',
        'unit': 'мм/с²',
        'scale': 1,
        'signed': False,
        'min': 100,
        'max': 50000,
        'default': 25000,
        'group': 0,
        'apply': 'idle',
        'info': '⚠ max вне слова W (±32767, RL 12-2) и выше предела DecL 25000 (RL 2-8) — вопрос GATE-0',
        'gate1': False,
    },
    4: {
        'name': 'P_SPD_J',
        'label': 'SpdJ',
        'unit': '%',
        'scale': 1,
        'signed': False,
        'min': 1,
        'max': 100,
        'default': 70,
        'group': 0,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    5: {
        'name': 'P_ACC_J',
        'label': 'AccJ/DecJ',
        'unit': '%',
        'scale': 1,
        'signed': False,
        'min': 1,
        'max': 100,
        'default': 100,
        'group': 0,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    6: {
        'name': 'P_OVERLAP',
        'label': 'SetOverlapDistance для LINE_PASS',
        'unit': 'мм',
        'scale': 10,
        'signed': False,
        'min': 1,
        'max': 100,
        'default': 5,
        'group': 0,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    7: {
        'name': 'P_ACCUR_DEFAULT',
        'label': 'Accur: 0 ROUGH / 1 HIGH',
        'unit': '',
        'scale': 1,
        'signed': False,
        'min': 0,
        'max': 1,
        'default': 0,
        'group': 0,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    8: {
        'name': 'P_JOG_MAX',
        'label': 'Максимум одного JOG-шага',
        'unit': 'мм',
        'scale': 10,
        'signed': False,
        'min': 1,
        'max': 5000,
        'default': 2000,
        'group': 0,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    9: {
        'name': 'P_HAND',
        'label': 'Рука точек прошивки: 0 правая / 1 левая (RL 5-3)',
        'unit': '',
        'scale': 1,
        'signed': False,
        'min': 0,
        'max': 1,
        'default': 1,
        'group': 0,
        'apply': 'idle',
        'info': '1 — как v1',
        'gate1': True,
    },
    10: {
        'name': 'P_JOG_CONT_MAX',
        'label': 'Предел скорости непрерывного jog',
        'unit': 'мм/с',
        'scale': 1,
        'signed': False,
        'min': 1,
        'max': 250,
        'default': 50,
        'group': 0,
        'apply': 'live',
        'info': 'для осей RZ+/RZ− — °/с',
        'gate1': False,
    },
    11: {
        'name': 'P_JOG_LEASE_MS',
        'label': 'Поводок jog: JOG_LEASE не менялся дольше — стоп',
        'unit': 'мс',
        'scale': 1,
        'signed': False,
        'min': 300,
        'max': 2000,
        'default': 300,
        'group': 0,
        'apply': 'live',
        'info': 'ПК пишет поводок не реже раза в треть срока',
        'gate1': False,
    },
    12: {
        'name': 'P_DEC_STOP',
        'label': 'Замедление стопа HARD',
        'unit': 'мм/с²',
        'scale': 1,
        'signed': False,
        'min': 1000,
        'max': 25000,
        'default': 25000,
        'group': 0,
        'apply': 'idle',
        'info': '25000 — максимум DecL, RL 2-8',
        'gate1': False,
    },
    16: {
        'name': 'P_HOME_X',
        'label': 'Дом X',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': 3000,
        'group': 1,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    17: {
        'name': 'P_HOME_Y',
        'label': 'Дом Y',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -2100,
        'group': 1,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    18: {
        'name': 'P_HOME_Z',
        'label': 'Дом Z',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -400,
        'group': 1,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    19: {
        'name': 'P_HOME_RZ',
        'label': 'Дом RZ',
        'unit': '°',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -1000,
        'group': 1,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    20: {
        'name': 'P_PLACE_X',
        'label': 'Укладка по умолчанию X',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': 4500,
        'group': 1,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    21: {
        'name': 'P_PLACE_Y',
        'label': 'Укладка по умолчанию Y',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -3000,
        'group': 1,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    22: {
        'name': 'P_PLACE_Z',
        'label': 'Укладка по умолчанию Z',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -900,
        'group': 1,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    23: {
        'name': 'P_PLACE_RZ',
        'label': 'Укладка по умолчанию RZ',
        'unit': '°',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -1000,
        'group': 1,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    24: {
        'name': 'P_PICK_Z',
        'label': 'Глубина забора по умолчанию',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -1000,
        'group': 1,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    25: {
        'name': 'P_PICK_RZ',
        'label': 'Угол при заборе',
        'unit': '°',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -1000,
        'group': 1,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    32: {
        'name': 'P_GRIP_MS',
        'label': 'Дожим захвата/отпускания',
        'unit': 'мс',
        'scale': 1,
        'signed': False,
        'min': 0,
        'max': 5000,
        'default': 400,
        'group': 2,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    33: {
        'name': 'P_ZONE_MIN',
        'label': 'Кольцо зоны забора, внутр.',
        'unit': 'мм',
        'scale': 10,
        'signed': False,
        'min': 0,
        'max': 32767,
        'default': 1200,
        'group': 2,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    34: {
        'name': 'P_ZONE_MAX',
        'label': 'Кольцо зоны забора, внеш.',
        'unit': 'мм',
        'scale': 10,
        'signed': False,
        'min': 0,
        'max': 32767,
        'default': 5000,
        'group': 2,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    35: {
        'name': 'P_BELT_FACTOR',
        'label': 'Ход ленты на импульс энкодера',
        'unit': 'мм/имп ×1e-5',
        'scale': 1,
        'signed': False,
        'min': 1,
        'max': 65535,
        'default': 14447,
        'group': 2,
        'apply': 'reinit',
        'info': '⚠ противоречит диапазону слова W (±32767, RL 12-2) — вопрос GATE-0',
        'gate1': False,
    },
    36: {
        'name': 'P_BELT_DIR',
        'label': 'Направление ленты: +X / +Y / -X / -Y',
        'unit': '',
        'scale': 1,
        'signed': False,
        'min': 0,
        'max': 3,
        'default': 1,
        'group': 2,
        'apply': 'reinit',
        'info': '',
        'gate1': False,
    },
    37: {
        'name': 'P_TRIG_X',
        'label': 'Линия срабатывания робота X',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': 3346,
        'group': 2,
        'apply': 'reinit',
        'info': '',
        'gate1': False,
    },
    38: {
        'name': 'P_TRIG_Y',
        'label': 'Линия срабатывания робота Y',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -3811,
        'group': 2,
        'apply': 'reinit',
        'info': '',
        'gate1': False,
    },
    39: {
        'name': 'P_ZONE_END_X',
        'label': 'Линия конца зоны X',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': 3346,
        'group': 2,
        'apply': 'reinit',
        'info': '',
        'gate1': False,
    },
    40: {
        'name': 'P_ZONE_END_Y',
        'label': 'Линия конца зоны Y',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -2000,
        'group': 2,
        'apply': 'reinit',
        'info': '',
        'gate1': False,
    },
    41: {
        'name': 'P_NG_RADIUS',
        'label': 'NGZoneRadius',
        'unit': 'мм',
        'scale': 10,
        'signed': False,
        'min': 0,
        'max': 32767,
        'default': 200,
        'group': 2,
        'apply': 'reinit',
        'info': 'единицы сверить на GATE-1',
        'gate1': False,
    },
    42: {
        'name': 'P_DO_GRIP_CH',
        'label': 'DO захвата для CVT_JOB',
        'unit': 'канал',
        'scale': 1,
        'signed': False,
        'min': 1,
        'max': 16,
        'default': 1,
        'group': 2,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    48: {
        'name': 'P_WS_R_MIN',
        'label': 'Внутренний радиус (мёртвая зона J1)',
        'unit': 'мм',
        'scale': 10,
        'signed': False,
        'min': 0,
        'max': 32767,
        'default': 1000,
        'group': 3,
        'apply': 'idle',
        'info': '⚠ по паспорту модели, GATE-1',
        'gate1': True,
    },
    49: {
        'name': 'P_WS_R_MAX',
        'label': 'Досягаемость',
        'unit': 'мм',
        'scale': 10,
        'signed': False,
        'min': 0,
        'max': 32767,
        'default': 6000,
        'group': 3,
        'apply': 'idle',
        'info': '⚠ по паспорту модели, GATE-1',
        'gate1': True,
    },
    50: {
        'name': 'P_WS_Z_MIN',
        'label': 'Мин. Z рабочей зоны',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -1500,
        'group': 3,
        'apply': 'idle',
        'info': '⚠ по паспорту модели, GATE-1',
        'gate1': True,
    },
    51: {
        'name': 'P_WS_Z_MAX',
        'label': 'Макс. Z рабочей зоны',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': 0,
        'group': 3,
        'apply': 'idle',
        'info': '⚠ по паспорту модели, GATE-1',
        'gate1': True,
    },
    52: {
        'name': 'P_WS_RZ_MIN',
        'label': 'Мин. RZ рабочей зоны',
        'unit': '°',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -3600,
        'group': 3,
        'apply': 'idle',
        'info': '⚠ по паспорту модели, GATE-1',
        'gate1': True,
    },
    53: {
        'name': 'P_WS_RZ_MAX',
        'label': 'Макс. RZ рабочей зоны',
        'unit': '°',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': 3600,
        'group': 3,
        'apply': 'idle',
        'info': '⚠ по паспорту модели, GATE-1',
        'gate1': True,
    },
    54: {
        'name': 'P_WS_BOX_EN',
        'label': 'Включить прямоугольник-ограждение',
        'unit': '',
        'scale': 1,
        'signed': False,
        'min': 0,
        'max': 1,
        'default': 0,
        'group': 3,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    55: {
        'name': 'P_WS_X_MIN',
        'label': 'Ограждение, X мин.',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -6000,
        'group': 3,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    56: {
        'name': 'P_WS_X_MAX',
        'label': 'Ограждение, X макс.',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': 6000,
        'group': 3,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    57: {
        'name': 'P_WS_Y_MIN',
        'label': 'Ограждение, Y мин.',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': -6000,
        'group': 3,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    58: {
        'name': 'P_WS_Y_MAX',
        'label': 'Ограждение, Y макс.',
        'unit': 'мм',
        'scale': 10,
        'signed': True,
        'min': -32767,
        'max': 32767,
        'default': 6000,
        'group': 3,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    59: {
        'name': 'P_WS_ANG_MIN',
        'label': 'Мин. угла сектора atan2(y, x)',
        'unit': '°',
        'scale': 10,
        'signed': True,
        'min': -1800,
        'max': 1800,
        'default': -1650,
        'group': 3,
        'apply': 'idle',
        'info': 'заглушка до модели с шильдика (plan §9 вопрос 1), ⚑ GATE-1',
        'gate1': True,
    },
    60: {
        'name': 'P_WS_ANG_MAX',
        'label': 'Макс. угла сектора atan2(y, x)',
        'unit': '°',
        'scale': 10,
        'signed': True,
        'min': -1800,
        'max': 1800,
        'default': 1650,
        'group': 3,
        'apply': 'idle',
        'info': 'заглушка до модели с шильдика (plan §9 вопрос 1), ⚑ GATE-1',
        'gate1': True,
    },
    64: {
        'name': 'P_VFD_PROFILE',
        'label': 'Профиль ПЧ: 0 = INVT GD20',
        'unit': '',
        'scale': 1,
        'signed': False,
        'min': 0,
        'max': 0,
        'default': 0,
        'group': 4,
        'apply': 'reinit',
        'info': '',
        'gate1': False,
    },
    65: {
        'name': 'P_VFD_SLAVE',
        'label': 'Адрес slave ПЧ',
        'unit': 'адрес',
        'scale': 1,
        'signed': False,
        'min': 1,
        'max': 247,
        'default': 1,
        'group': 4,
        'apply': 'reinit',
        'info': '',
        'gate1': False,
    },
    66: {
        'name': 'P_VFD_BAUD',
        'label': 'Скорость порта ПЧ',
        'unit': 'код',
        'scale': 1,
        'signed': False,
        'min': 0,
        'max': 32767,
        'default': 2,
        'group': 4,
        'apply': 'reinit',
        'info': 'как SCM_FreePort',
        'gate1': False,
    },
    67: {
        'name': 'P_VFD_FRAME',
        'label': 'Формат кадра ПЧ',
        'unit': 'код',
        'scale': 1,
        'signed': False,
        'min': 0,
        'max': 32767,
        'default': 13,
        'group': 4,
        'apply': 'reinit',
        'info': 'как SCM_FreePort; v1: 0xD',
        'gate1': False,
    },
    68: {
        'name': 'P_VFD_MODE',
        'label': 'Режим порта ПЧ',
        'unit': 'код',
        'scale': 1,
        'signed': False,
        'min': 0,
        'max': 32767,
        'default': 17,
        'group': 4,
        'apply': 'reinit',
        'info': 'как SCM_FreePort; v1: 0x11',
        'gate1': False,
    },
    69: {
        'name': 'P_VFD_POLL_MS',
        'label': 'Период опроса статуса ПЧ',
        'unit': 'мс',
        'scale': 1,
        'signed': False,
        'min': 50,
        'max': 5000,
        'default': 300,
        'group': 4,
        'apply': 'live',
        'info': '',
        'gate1': False,
    },
    70: {
        'name': 'P_VFD_RX_TRIES',
        'label': 'Попыток приёма по 5 мс',
        'unit': 'раз',
        'scale': 1,
        'signed': False,
        'min': 1,
        'max': 50,
        'default': 8,
        'group': 4,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    71: {
        'name': 'P_VFD_LINK_FAILS',
        'label': 'Сколько неответов подряд = обрыв',
        'unit': 'раз',
        'scale': 1,
        'signed': False,
        'min': 1,
        'max': 100,
        'default': 5,
        'group': 4,
        'apply': 'idle',
        'info': '',
        'gate1': False,
    },
    96: {
        'name': 'P_WDG_TIMEOUT_MS',
        'label': 'Таймаут сторожевого таймера, 0 — выключен',
        'unit': 'мс',
        'scale': 1,
        'signed': False,
        'min': 0,
        'max': 60000,
        'default': 3000,
        'group': 6,
        'apply': 'live',
        'info': '⚠ max вне слова W (±32767, RL 12-2) — вопрос GATE-0',
        'gate1': False,
    },
    97: {
        'name': 'P_TLM_EVERY',
        'label': 'Частота публикации телеметрии в простое',
        'unit': 'циклов',
        'scale': 1,
        'signed': False,
        'min': 1,
        'max': 100,
        'default': 5,
        'group': 6,
        'apply': 'live',
        'info': '',
        'gate1': False,
    },
    98: {
        'name': 'P_CONFIG_EPOCH',
        'label': 'Метка конфигурации ПК (§11.4)',
        'unit': '',
        'scale': 1,
        'signed': False,
        'min': 0,
        'max': 65535,
        'default': 0,
        'group': 6,
        'apply': 'live',
        'info': '⚠ противоречит диапазону слова W (±32767, RL 12-2) — вопрос GATE-0',
        'gate1': False,
    },
}

PARAM_ID = {
    'P_SPD_DEFAULT': 0,
    'P_SPD_JOG': 1,
    'P_SPD_L': 2,
    'P_ACC_L': 3,
    'P_SPD_J': 4,
    'P_ACC_J': 5,
    'P_OVERLAP': 6,
    'P_ACCUR_DEFAULT': 7,
    'P_JOG_MAX': 8,
    'P_HAND': 9,
    'P_JOG_CONT_MAX': 10,
    'P_JOG_LEASE_MS': 11,
    'P_DEC_STOP': 12,
    'P_HOME_X': 16,
    'P_HOME_Y': 17,
    'P_HOME_Z': 18,
    'P_HOME_RZ': 19,
    'P_PLACE_X': 20,
    'P_PLACE_Y': 21,
    'P_PLACE_Z': 22,
    'P_PLACE_RZ': 23,
    'P_PICK_Z': 24,
    'P_PICK_RZ': 25,
    'P_GRIP_MS': 32,
    'P_ZONE_MIN': 33,
    'P_ZONE_MAX': 34,
    'P_BELT_FACTOR': 35,
    'P_BELT_DIR': 36,
    'P_TRIG_X': 37,
    'P_TRIG_Y': 38,
    'P_ZONE_END_X': 39,
    'P_ZONE_END_Y': 40,
    'P_NG_RADIUS': 41,
    'P_DO_GRIP_CH': 42,
    'P_WS_R_MIN': 48,
    'P_WS_R_MAX': 49,
    'P_WS_Z_MIN': 50,
    'P_WS_Z_MAX': 51,
    'P_WS_RZ_MIN': 52,
    'P_WS_RZ_MAX': 53,
    'P_WS_BOX_EN': 54,
    'P_WS_X_MIN': 55,
    'P_WS_X_MAX': 56,
    'P_WS_Y_MIN': 57,
    'P_WS_Y_MAX': 58,
    'P_WS_ANG_MIN': 59,
    'P_WS_ANG_MAX': 60,
    'P_VFD_PROFILE': 64,
    'P_VFD_SLAVE': 65,
    'P_VFD_BAUD': 66,
    'P_VFD_FRAME': 67,
    'P_VFD_MODE': 68,
    'P_VFD_POLL_MS': 69,
    'P_VFD_RX_TRIES': 70,
    'P_VFD_LINK_FAILS': 71,
    'P_WDG_TIMEOUT_MS': 96,
    'P_TLM_EVERY': 97,
    'P_CONFIG_EPOCH': 98,
}

GROUPS = {
    0: {
        'name': 'motion',
        'label': 'Движение',
    },
    1: {
        'name': 'points',
        'label': 'Точки',
    },
    2: {
        'name': 'cvt',
        'label': 'Конвейер (CVT)',
    },
    3: {
        'name': 'workspace',
        'label': 'Рабочая зона',
    },
    4: {
        'name': 'vfd',
        'label': 'ПЧ',
    },
    6: {
        'name': 'system',
        'label': 'Система',
    },
}

DICT_FINGERPRINT = 23080

def to_eng(name: str, raw: float) -> float:
    """Сырое значение параметра -> инженерные единицы (raw / scale)."""
    return raw / PARAMS[PARAM_ID[name]]["scale"]

def to_raw(name: str, eng: float) -> int:
    """Инженерные единицы -> сырое значение (округление до ближайшего от нуля)."""
    scale = PARAMS[PARAM_ID[name]]["scale"]
    x = eng * scale
    magnitude = int(math.floor(abs(x) + 0.5))
    return -magnitude if x < 0 else magnitude

class RobotParamsV2(SchemaBase):
    """Параметры робота Delta v2 — по одному полю на запись словаря (params.md §11.3)."""

    spd_default: Annotated[
        int,
        Field(default=80),
        FieldMeta(
            'Override по умолчанию',
            unit='%',
            min=1,
            max=100,
            info='',
            ui_group='motion',
            ui_order=0,
        ),
    ]

    spd_jog: Annotated[
        int,
        Field(default=30),
        FieldMeta(
            'Override для JOG',
            unit='%',
            min=1,
            max=100,
            info='',
            ui_group='motion',
            ui_order=1,
        ),
    ]

    spd_l: Annotated[
        int,
        Field(default=1500),
        FieldMeta(
            'SpdL',
            unit='мм/с',
            min=10,
            max=3000,
            info='',
            ui_group='motion',
            ui_order=2,
        ),
    ]

    acc_l: Annotated[
        int,
        Field(default=25000),
        FieldMeta(
            'AccL/DecL',
            unit='мм/с²',
            min=100,
            max=50000,
            info='⚠ max вне слова W (±32767, RL 12-2) и выше предела DecL 25000 (RL 2-8) — вопрос GATE-0',
            ui_group='motion',
            ui_order=3,
        ),
    ]

    spd_j: Annotated[
        int,
        Field(default=70),
        FieldMeta(
            'SpdJ',
            unit='%',
            min=1,
            max=100,
            info='',
            ui_group='motion',
            ui_order=4,
        ),
    ]

    acc_j: Annotated[
        int,
        Field(default=100),
        FieldMeta(
            'AccJ/DecJ',
            unit='%',
            min=1,
            max=100,
            info='',
            ui_group='motion',
            ui_order=5,
        ),
    ]

    overlap: Annotated[
        float,
        Field(default=0.5),
        FieldMeta(
            'SetOverlapDistance для LINE_PASS',
            unit='мм',
            min=0.1,
            max=10.0,
            info='',
            ui_group='motion',
            ui_order=6,
            round_k=1,
        ),
    ]

    accur_default: Annotated[
        int,
        Field(default=0),
        FieldMeta(
            'Accur: 0 ROUGH / 1 HIGH',
            unit='',
            min=0,
            max=1,
            info='',
            ui_group='motion',
            ui_order=7,
        ),
    ]

    jog_max: Annotated[
        float,
        Field(default=200.0),
        FieldMeta(
            'Максимум одного JOG-шага',
            unit='мм',
            min=0.1,
            max=500.0,
            info='',
            ui_group='motion',
            ui_order=8,
            round_k=1,
        ),
    ]

    hand: Annotated[
        int,
        Field(default=1),
        FieldMeta(
            'Рука точек прошивки: 0 правая / 1 левая (RL 5-3)',
            unit='',
            min=0,
            max=1,
            info='1 — как v1',
            ui_group='motion',
            ui_order=9,
        ),
    ]

    jog_cont_max: Annotated[
        int,
        Field(default=50),
        FieldMeta(
            'Предел скорости непрерывного jog',
            unit='мм/с',
            min=1,
            max=250,
            info='для осей RZ+/RZ− — °/с',
            ui_group='motion',
            ui_order=10,
        ),
    ]

    jog_lease_ms: Annotated[
        int,
        Field(default=300),
        FieldMeta(
            'Поводок jog: JOG_LEASE не менялся дольше — стоп',
            unit='мс',
            min=300,
            max=2000,
            info='ПК пишет поводок не реже раза в треть срока',
            ui_group='motion',
            ui_order=11,
        ),
    ]

    dec_stop: Annotated[
        int,
        Field(default=25000),
        FieldMeta(
            'Замедление стопа HARD',
            unit='мм/с²',
            min=1000,
            max=25000,
            info='25000 — максимум DecL, RL 2-8',
            ui_group='motion',
            ui_order=12,
        ),
    ]

    home_x: Annotated[
        float,
        Field(default=300.0),
        FieldMeta(
            'Дом X',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='points',
            ui_order=16,
            round_k=1,
        ),
    ]

    home_y: Annotated[
        float,
        Field(default=-210.0),
        FieldMeta(
            'Дом Y',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='points',
            ui_order=17,
            round_k=1,
        ),
    ]

    home_z: Annotated[
        float,
        Field(default=-40.0),
        FieldMeta(
            'Дом Z',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='points',
            ui_order=18,
            round_k=1,
        ),
    ]

    home_rz: Annotated[
        float,
        Field(default=-100.0),
        FieldMeta(
            'Дом RZ',
            unit='°',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='points',
            ui_order=19,
            round_k=1,
        ),
    ]

    place_x: Annotated[
        float,
        Field(default=450.0),
        FieldMeta(
            'Укладка по умолчанию X',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='points',
            ui_order=20,
            round_k=1,
        ),
    ]

    place_y: Annotated[
        float,
        Field(default=-300.0),
        FieldMeta(
            'Укладка по умолчанию Y',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='points',
            ui_order=21,
            round_k=1,
        ),
    ]

    place_z: Annotated[
        float,
        Field(default=-90.0),
        FieldMeta(
            'Укладка по умолчанию Z',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='points',
            ui_order=22,
            round_k=1,
        ),
    ]

    place_rz: Annotated[
        float,
        Field(default=-100.0),
        FieldMeta(
            'Укладка по умолчанию RZ',
            unit='°',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='points',
            ui_order=23,
            round_k=1,
        ),
    ]

    pick_z: Annotated[
        float,
        Field(default=-100.0),
        FieldMeta(
            'Глубина забора по умолчанию',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='points',
            ui_order=24,
            round_k=1,
        ),
    ]

    pick_rz: Annotated[
        float,
        Field(default=-100.0),
        FieldMeta(
            'Угол при заборе',
            unit='°',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='points',
            ui_order=25,
            round_k=1,
        ),
    ]

    grip_ms: Annotated[
        int,
        Field(default=400),
        FieldMeta(
            'Дожим захвата/отпускания',
            unit='мс',
            min=0,
            max=5000,
            info='',
            ui_group='cvt',
            ui_order=32,
        ),
    ]

    zone_min: Annotated[
        float,
        Field(default=120.0),
        FieldMeta(
            'Кольцо зоны забора, внутр.',
            unit='мм',
            min=0.0,
            max=3276.7,
            info='',
            ui_group='cvt',
            ui_order=33,
            round_k=1,
        ),
    ]

    zone_max: Annotated[
        float,
        Field(default=500.0),
        FieldMeta(
            'Кольцо зоны забора, внеш.',
            unit='мм',
            min=0.0,
            max=3276.7,
            info='',
            ui_group='cvt',
            ui_order=34,
            round_k=1,
        ),
    ]

    belt_factor: Annotated[
        int,
        Field(default=14447),
        FieldMeta(
            'Ход ленты на импульс энкодера',
            unit='мм/имп ×1e-5',
            min=1,
            max=65535,
            info='⚠ противоречит диапазону слова W (±32767, RL 12-2) — вопрос GATE-0',
            ui_group='cvt',
            ui_order=35,
        ),
    ]

    belt_dir: Annotated[
        int,
        Field(default=1),
        FieldMeta(
            'Направление ленты: +X / +Y / -X / -Y',
            unit='',
            min=0,
            max=3,
            info='',
            ui_group='cvt',
            ui_order=36,
        ),
    ]

    trig_x: Annotated[
        float,
        Field(default=334.6),
        FieldMeta(
            'Линия срабатывания робота X',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='cvt',
            ui_order=37,
            round_k=1,
        ),
    ]

    trig_y: Annotated[
        float,
        Field(default=-381.1),
        FieldMeta(
            'Линия срабатывания робота Y',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='cvt',
            ui_order=38,
            round_k=1,
        ),
    ]

    zone_end_x: Annotated[
        float,
        Field(default=334.6),
        FieldMeta(
            'Линия конца зоны X',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='cvt',
            ui_order=39,
            round_k=1,
        ),
    ]

    zone_end_y: Annotated[
        float,
        Field(default=-200.0),
        FieldMeta(
            'Линия конца зоны Y',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='cvt',
            ui_order=40,
            round_k=1,
        ),
    ]

    ng_radius: Annotated[
        float,
        Field(default=20.0),
        FieldMeta(
            'NGZoneRadius',
            unit='мм',
            min=0.0,
            max=3276.7,
            info='единицы сверить на GATE-1',
            ui_group='cvt',
            ui_order=41,
            round_k=1,
        ),
    ]

    do_grip_ch: Annotated[
        int,
        Field(default=1),
        FieldMeta(
            'DO захвата для CVT_JOB',
            unit='канал',
            min=1,
            max=16,
            info='',
            ui_group='cvt',
            ui_order=42,
        ),
    ]

    ws_r_min: Annotated[
        float,
        Field(default=100.0),
        FieldMeta(
            'Внутренний радиус (мёртвая зона J1)',
            unit='мм',
            min=0.0,
            max=3276.7,
            info='⚠ по паспорту модели, GATE-1',
            ui_group='workspace',
            ui_order=48,
            round_k=1,
        ),
    ]

    ws_r_max: Annotated[
        float,
        Field(default=600.0),
        FieldMeta(
            'Досягаемость',
            unit='мм',
            min=0.0,
            max=3276.7,
            info='⚠ по паспорту модели, GATE-1',
            ui_group='workspace',
            ui_order=49,
            round_k=1,
        ),
    ]

    ws_z_min: Annotated[
        float,
        Field(default=-150.0),
        FieldMeta(
            'Мин. Z рабочей зоны',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='⚠ по паспорту модели, GATE-1',
            ui_group='workspace',
            ui_order=50,
            round_k=1,
        ),
    ]

    ws_z_max: Annotated[
        float,
        Field(default=0.0),
        FieldMeta(
            'Макс. Z рабочей зоны',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='⚠ по паспорту модели, GATE-1',
            ui_group='workspace',
            ui_order=51,
            round_k=1,
        ),
    ]

    ws_rz_min: Annotated[
        float,
        Field(default=-360.0),
        FieldMeta(
            'Мин. RZ рабочей зоны',
            unit='°',
            min=-3276.7,
            max=3276.7,
            info='⚠ по паспорту модели, GATE-1',
            ui_group='workspace',
            ui_order=52,
            round_k=1,
        ),
    ]

    ws_rz_max: Annotated[
        float,
        Field(default=360.0),
        FieldMeta(
            'Макс. RZ рабочей зоны',
            unit='°',
            min=-3276.7,
            max=3276.7,
            info='⚠ по паспорту модели, GATE-1',
            ui_group='workspace',
            ui_order=53,
            round_k=1,
        ),
    ]

    ws_box_en: Annotated[
        int,
        Field(default=0),
        FieldMeta(
            'Включить прямоугольник-ограждение',
            unit='',
            min=0,
            max=1,
            info='',
            ui_group='workspace',
            ui_order=54,
        ),
    ]

    ws_x_min: Annotated[
        float,
        Field(default=-600.0),
        FieldMeta(
            'Ограждение, X мин.',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='workspace',
            ui_order=55,
            round_k=1,
        ),
    ]

    ws_x_max: Annotated[
        float,
        Field(default=600.0),
        FieldMeta(
            'Ограждение, X макс.',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='workspace',
            ui_order=56,
            round_k=1,
        ),
    ]

    ws_y_min: Annotated[
        float,
        Field(default=-600.0),
        FieldMeta(
            'Ограждение, Y мин.',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='workspace',
            ui_order=57,
            round_k=1,
        ),
    ]

    ws_y_max: Annotated[
        float,
        Field(default=600.0),
        FieldMeta(
            'Ограждение, Y макс.',
            unit='мм',
            min=-3276.7,
            max=3276.7,
            info='',
            ui_group='workspace',
            ui_order=58,
            round_k=1,
        ),
    ]

    ws_ang_min: Annotated[
        float,
        Field(default=-165.0),
        FieldMeta(
            'Мин. угла сектора atan2(y, x)',
            unit='°',
            min=-180.0,
            max=180.0,
            info='заглушка до модели с шильдика (plan §9 вопрос 1), ⚑ GATE-1',
            ui_group='workspace',
            ui_order=59,
            round_k=1,
        ),
    ]

    ws_ang_max: Annotated[
        float,
        Field(default=165.0),
        FieldMeta(
            'Макс. угла сектора atan2(y, x)',
            unit='°',
            min=-180.0,
            max=180.0,
            info='заглушка до модели с шильдика (plan §9 вопрос 1), ⚑ GATE-1',
            ui_group='workspace',
            ui_order=60,
            round_k=1,
        ),
    ]

    vfd_profile: Annotated[
        int,
        Field(default=0),
        FieldMeta(
            'Профиль ПЧ: 0 = INVT GD20',
            unit='',
            min=0,
            max=0,
            info='',
            ui_group='vfd',
            ui_order=64,
        ),
    ]

    vfd_slave: Annotated[
        int,
        Field(default=1),
        FieldMeta(
            'Адрес slave ПЧ',
            unit='адрес',
            min=1,
            max=247,
            info='',
            ui_group='vfd',
            ui_order=65,
        ),
    ]

    vfd_baud: Annotated[
        int,
        Field(default=2),
        FieldMeta(
            'Скорость порта ПЧ',
            unit='код',
            min=0,
            max=32767,
            info='как SCM_FreePort',
            ui_group='vfd',
            ui_order=66,
        ),
    ]

    vfd_frame: Annotated[
        int,
        Field(default=13),
        FieldMeta(
            'Формат кадра ПЧ',
            unit='код',
            min=0,
            max=32767,
            info='как SCM_FreePort; v1: 0xD',
            ui_group='vfd',
            ui_order=67,
        ),
    ]

    vfd_mode: Annotated[
        int,
        Field(default=17),
        FieldMeta(
            'Режим порта ПЧ',
            unit='код',
            min=0,
            max=32767,
            info='как SCM_FreePort; v1: 0x11',
            ui_group='vfd',
            ui_order=68,
        ),
    ]

    vfd_poll_ms: Annotated[
        int,
        Field(default=300),
        FieldMeta(
            'Период опроса статуса ПЧ',
            unit='мс',
            min=50,
            max=5000,
            info='',
            ui_group='vfd',
            ui_order=69,
        ),
    ]

    vfd_rx_tries: Annotated[
        int,
        Field(default=8),
        FieldMeta(
            'Попыток приёма по 5 мс',
            unit='раз',
            min=1,
            max=50,
            info='',
            ui_group='vfd',
            ui_order=70,
        ),
    ]

    vfd_link_fails: Annotated[
        int,
        Field(default=5),
        FieldMeta(
            'Сколько неответов подряд = обрыв',
            unit='раз',
            min=1,
            max=100,
            info='',
            ui_group='vfd',
            ui_order=71,
        ),
    ]

    wdg_timeout_ms: Annotated[
        int,
        Field(default=3000),
        FieldMeta(
            'Таймаут сторожевого таймера, 0 — выключен',
            unit='мс',
            min=0,
            max=60000,
            info='⚠ max вне слова W (±32767, RL 12-2) — вопрос GATE-0',
            ui_group='system',
            ui_order=96,
        ),
    ]

    tlm_every: Annotated[
        int,
        Field(default=5),
        FieldMeta(
            'Частота публикации телеметрии в простое',
            unit='циклов',
            min=1,
            max=100,
            info='',
            ui_group='system',
            ui_order=97,
        ),
    ]

    config_epoch: Annotated[
        int,
        Field(default=0),
        FieldMeta(
            'Метка конфигурации ПК (§11.4)',
            unit='',
            min=0,
            max=65535,
            info='⚠ противоречит диапазону слова W (±32767, RL 12-2) — вопрос GATE-0',
            ui_group='system',
            ui_order=98,
        ),
    ]
