"""registry.py — общий механизм замены маркеров и применения sync-модулей.

Портировано из Inspector_bottles/scripts/sync/registry.py с минимальными
правками (generic-имена, расширенные docstrings). Источник pattern'а —
auto-sync per-module markdown в большом проекте.

Определяет:
- MarkerNotFound — исключение при отсутствии маркеров в тексте.
- SyncModule — Protocol для sync-модулей (render_context, render_adr, …).
- replace_between_markers — замена содержимого между маркерными комментариями.
- apply_sync — итерация по модулям, render + replace (или check + diff).
"""

from __future__ import annotations

import difflib
import re
import sys
from pathlib import Path
from typing import Protocol, runtime_checkable


class MarkerNotFound(Exception):
    """Маркер BEGIN или END не найден в тексте.

    Сообщение содержит ключ маркера и (при наличии) имя файла,
    чтобы разработчик мог быстро найти проблему.
    """


@runtime_checkable
class SyncModule(Protocol):
    """Контракт sync-модуля.

    Каждый sync-модуль предоставляет:
      - name — уникальный идентификатор ('render_context', 'render_adr', …).
      - description — человекочитаемое описание (для --list).
      - render() — словарь {путь_к_файлу: {ключ_маркера: сгенерированный_контент}}.

    Pre:
      - name unique across registered modules
      - render() возвращает пустой dict если нечего рендерить (не падает)
    Post:
      - render() детерминирован (одинаковый input → одинаковый output)
    """

    @property
    def name(self) -> str: ...

    @property
    def description(self) -> str: ...

    def render(self) -> dict[Path, dict[str, str]]: ...


def replace_between_markers(
    text: str,
    key: str,
    content: str,
    *,
    filename: str = "<текст>",
) -> str:
    """Заменяет содержимое между маркерами BEGIN и END на *content*.

    Маркеры сохраняются как есть (включая описание в BEGIN-теге).
    Между BEGIN и END помещается *content* (с переводом строки до и после).

    Args:
        text: исходный текст файла.
        key: ключ маркера (например, 'CONTEXT-INDEX', 'ADR-CODES').
        content: новое содержимое для вставки между маркерами.
        filename: имя файла для сообщений об ошибках.

    Returns:
        Текст с заменённым содержимым между маркерами.

    Raises:
        MarkerNotFound: если BEGIN- или END-маркер не найден.

    Pre:
      - key содержит только [A-Za-z0-9_-]
    Post:
      - результат содержит ровно один BEGIN и один END маркер
      - текст вне маркеров не изменён байт-в-байт
    """
    begin_re = re.compile(
        rf"^(<!-- {re.escape(key)}:BEGIN\b[^>]*-->)[ \t]*$",
        re.MULTILINE,
    )
    end_re = re.compile(
        rf"^(<!-- {re.escape(key)}:END\s*-->)[ \t]*$",
        re.MULTILINE,
    )

    begin_match = begin_re.search(text)
    if begin_match is None:
        raise MarkerNotFound(
            f"Маркер «{key}:BEGIN» не найден в файле «{filename}». "
            f"Добавь строку вида: <!-- {key}:BEGIN — generated by aggregate_context — DO NOT EDIT -->"
        )

    end_match = end_re.search(text, begin_match.end())
    if end_match is None:
        raise MarkerNotFound(
            f"Маркер «{key}:END» не найден в файле «{filename}» "
            f"(BEGIN найден в позиции {begin_match.start()}). "
            f"Добавь строку: <!-- {key}:END -->"
        )

    before = text[: begin_match.end()]
    after = text[end_match.start() :]

    if content and not content.startswith("\n"):
        content = "\n" + content
    if content and not content.endswith("\n"):
        content = content + "\n"
    if not content:
        content = "\n"

    return before + content + after


def apply_sync(
    modules: list[SyncModule],
    *,
    check: bool,
    only: str | None = None,
) -> int:
    """Применяет sync-модули: write или check.

    Args:
        modules: список sync-модулей.
        check: если True — не пишет файлы, а сравнивает и печатает diff.
        only: если задано — фильтрует модули по name.

    Returns:
        0 — всё чисто (или записано); 1 — обнаружен дрифт (в check-режиме)
        или ошибка (отсутствующий файл, отсутствующий маркер).
    """
    if only is not None:
        modules = [m for m in modules if m.name == only]

    has_drift = False

    for mod in modules:
        rendered = mod.render()

        for file_path, markers in rendered.items():
            file_path = Path(file_path)

            if not file_path.exists():
                print(
                    f"[ОШИБКА] Файл не найден: {file_path} (модуль «{mod.name}»)",
                    file=sys.stderr,
                )
                has_drift = True
                continue

            original_text = file_path.read_text(encoding="utf-8")
            updated_text = original_text

            for marker_key, content in markers.items():
                try:
                    updated_text = replace_between_markers(
                        updated_text,
                        marker_key,
                        content,
                        filename=str(file_path),
                    )
                except MarkerNotFound as exc:
                    print(f"[ОШИБКА] {exc}", file=sys.stderr)
                    has_drift = True
                    continue

            if check:
                if updated_text != original_text:
                    has_drift = True
                    diff_lines = difflib.unified_diff(
                        original_text.splitlines(keepends=True),
                        updated_text.splitlines(keepends=True),
                        fromfile=f"a/{file_path}",
                        tofile=f"b/{file_path}",
                    )
                    sys.stderr.writelines(diff_lines)
            else:
                if updated_text != original_text:
                    file_path.write_text(updated_text, encoding="utf-8")
                    print(f"[ЗАПИСАНО] {file_path} (модуль «{mod.name}»)")

    return 1 if has_drift else 0
